name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Project Artifacts
        run: |
          echo "🔍 Starting build process..."
          echo "Node version: $(node --version)"
          echo "PNPM version: $(pnpm --version)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "🚀 Running Vercel build..."
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --debug

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Notify on Success
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "🚀 Your app should be live at your Vercel URL"

      - name: Fallback Notification on Failure
        if: failure()
        run: |
          echo "❌ AlignSynch Deployment Failed!"
          echo "🔍 Build Error Details:"
          echo "  - Commit: ${{ github.sha }}"
          echo "  - Branch: ${{ github.ref_name }}"
          echo "  - Workflow: ${{ github.workflow }}"
          echo "  - Run: ${{ github.run_number }}"
          echo "📝 Check logs at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
